### ISSUE TITLE
won't accept years as numerical

### ISSUE THREAD

**Issue by jormacmoo** [miyoungblood/miniproject3#1]
Whenever I try to make the preliminary tables, I get an error that says 'Decimal MySQL column 1 imported as numeric' and no rows in my table and I don't know why?

**Comment by miyoungblood** [comment]
db %>%
  dbGetQuery("SELECT t.production_year, sum(mi.info_type_id) AS num_R
             FROM title t
             JOIN movie_info mi ON t.id = mi.movie_id
             WHERE mi.info_type_id = 97
             AND info LIKE '%Rated R%'
             GROUP BY t.production_year;")
